#!/usr/bin/env ruby

require File.dirname(__FILE__) + '/../lib/dcop'

# Automatically builds the Amarok library based on everything available in amarok through dcop!
DCOP.build!('amarok', 'user' => 'jukeman', 'session' => '.DCOPserver_jukeman-elkhart__0')

# Begin the process!
# 1) Import the updates
  Journal.import_from_server
# 2) Apply database to Amarok
  Playlist.active.apply_to_amarok
