#!/usr/bin/env ruby

require File.dirname(__FILE__) + '/../config/boot'
require File.dirname(__FILE__) + '/../lib/dcop'

username = Dir.pwd.split('/')[2]
hostname = `cat /etc/hostname`.gsub(/\n|\r/, '')

# Automatically builds the Amarok library based on everything available in amarok through dcop!
DCOP.build!('amarok', 'user' => username, 'session' => '.DCOPserver_'+hostname+'__0')

# Begin the process!
# 1) Import the updates
  Journal.import_from_server
# 2) Apply database to Amarok
  Playlist.active.apply_to_amarok